export const FETCH_FUBO_PLANS_START = "FETCH_FUBO_PLANS_START";
export const FETCH_FUBO_PLANS_SUCCESS = "FETCH_FUBO_PLANS_SUCCESS";
export const FETCH_FUBO_PLANS_FAIL = "FETCH_FUBO_PLANS_FAIL";

export const CHANGE_TAB_VALUE_START = "CHANGE_TAB_VALUE_START";
export const CHANGE_TAB_VALUE = "CHANGE_TAB_VALUE";

